#!/usr/bin/python

# webkit2png - makes screenshots of webpages
# http://www.paranoidfish.org/projects/webkit2png
__version__ = "0.2"

# $Id$

# Copyright (C) 2004 Paul Hammond
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

from Foundation import *
import WebKit
from AppKit import *
import objc
import sys
from optparse import OptionParser
import re
import os
objc.setVerbose(1) ### DEBUG

class AppDelegate (NSObject):
   # what happens when the app starts up
   def applicationDidFinishLaunching_(self, aNotification):
        if self.URL != None:
          self.webView.mainFrame().loadRequest_(NSURLRequest.requestWithURL_(NSURL.URLWithString_(self.URL)))
        else:
          NSApplication.sharedApplication().terminate_(None)

class WebkitLoad (NSObject, WebKit.protocols.WebFrameLoadDelegate):
    # what happens if something goes wrong while loading
    def webView_didFailProvisionalLoadWithError_forFrame_(self,sender,error,frame):
       print "Something went wrong" 
       NSApplication.sharedApplication().terminate_(None)
    
    
    # what happens when the page has finished loading
    def webView_didFinishLoadForFrame_(self,sender,frame):
       # don't care about subframes
       if (frame == sender.mainFrame()):
           # resize the window and content to the natural size of the page
           view = frame.frameView().documentView()
           view.window().display()
           view.window().setContentSize_(view.bounds().size)
           view.setFrame_(view.bounds())
           
           # take a screenshot
           view.lockFocus()
           bitmapdata = NSBitmapImageRep.alloc()
           bitmapdata.initWithFocusedViewRect_(view.bounds())
           view.unlockFocus()
           
           # save the fullsize png
           bitmapdata.representationUsingType_properties_(NSPNGFileType,None).writeToFile_atomically_(self.filename + ".png",objc.YES)

           # work out how big the thumbnail is
           width = bitmapdata.pixelsWide()
           height = bitmapdata.pixelsHigh()
           thumbWidth = (width *self.scale)
           thumbHeight = (height *self.scale)

           # make the thumbnails in a scratch image
           scratch = NSImage.alloc().initWithSize_(NSMakeSize(thumbWidth,thumbHeight)).autorelease()
           scratch.lockFocus()
           NSGraphicsContext.currentContext().setImageInterpolation_(NSImageInterpolationHigh)
           thumbRect = NSMakeRect(0.0, 0.0, thumbWidth, thumbHeight)
           clipRect = NSMakeRect(0.0, thumbHeight-self.clipHeight, self.clipWidth, self.clipHeight)
           bitmapdata.drawInRect_(thumbRect)
           thumbOutput = NSBitmapImageRep.alloc().initWithFocusedViewRect_(thumbRect).autorelease()
           clipOutput = NSBitmapImageRep.alloc().initWithFocusedViewRect_(clipRect).autorelease()
           scratch.unlockFocus()

           # save the thumbnails as pngs 
           thumbOutput.representationUsingType_properties_(NSPNGFileType,None).writeToFile_atomically_(self.filename + "-thumb.png",objc.YES)
           clipOutput.representationUsingType_properties_(NSPNGFileType,None).writeToFile_atomically_(self.filename + "-clipped.png",objc.YES)

           NSApplication.sharedApplication().terminate_(None)


def main():

    # parse the command line
    cmdparser = OptionParser("usage: %prog [options] http://www.example.com", version=("webkit2png "+__version__))
    cmdparser.add_option("-W", "--width",type="float",default=800.0,
       help="initial width of content area (default: 800)")
    cmdparser.add_option("-H", "--height",type="float",default=600.0,
       help="initial height of content area (default: 600)")
    cmdparser.add_option("--clipwidth",type="float",default=200.0,
       help="width of clipped thumbnail (default: 200)")
    cmdparser.add_option("--clipheight",type="float",default=150.0,
       help="height of clipped thumbnail (default: 150)")
    cmdparser.add_option("-s", "--scale",type="float",default=0.25,
       help="scale factor for thumbnails (default: 0.25)")
    (options, args) = cmdparser.parse_args()
    if len(args) != 1:
      cmdparser.print_help()
      return

    # grab the url
    URL=args[0]
    # make the filename
    filename = re.sub('\W','',URL);
    filename = re.sub('^http','',filename);

    app = NSApplication.sharedApplication()
    
    # create an app delegate
    delegate = AppDelegate.alloc().init()
    NSApp().setDelegate_(delegate)

    # create a window
    rect = NSMakeRect(-16000.0,-16000.0,options.width,options.height)
    win = NSWindow.alloc()
    win.initWithContentRect_styleMask_backing_defer_ (rect, NSBorderlessWindowMask, 2, 0)

    # create a webview object
    webview = WebKit.WebView.alloc()
    webview.initWithFrame_(rect)
    # turn off scrolling so the content is actually x wide and not x-15
    webview.mainFrame().frameView().setAllowsScrolling_(objc.NO)
    # add the webview to the window
    win.setContentView_(webview)
    
    # create a LoadDelegate
    loaddelegate = WebkitLoad.alloc().init()
    loaddelegate.filename = filename
    loaddelegate.width = options.width
    loaddelegate.height = options.height
    loaddelegate.clipWidth = options.clipwidth
    loaddelegate.clipHeight = options.clipheight
    loaddelegate.scale = options.scale
    webview.setFrameLoadDelegate_(loaddelegate)
    
    # give the appdelegate some info
    delegate.webView = webview
    delegate.URL = URL
    
    win.display()
    app.run()    

if __name__ == '__main__' : main()
